# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Run_Tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  
  launch_jenkins_job:
    name: Trigger jenkins job
    runs-on: ubuntu-latest
    steps:
      - name: Jenkins job
        uses: jabbukka/jenkins-trigger@main
        with:
          url: http://52.195.218.174:8080/
          job_name: "Playwright sample"
          user_name: admin
          api_token: 1126df72b1f4776cffd9493af6ab4ca3cb
          wait: "true"
          timeout: "1000"
